version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 4000
    container_name: backend
    volumes:
      - "./backend:/srv/server"
    ports:
      - "4000:4000"
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./client:/srv/client"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:4000
    depends_on:
      - backend
