version: "3.8"
services:
  database:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_DATABASE: dopplr
      MONGO_INITDB_ROOT_USERNAME: dopplr
      MONGO_INITDB_ROOT_PASSWORD: dopplr
    volumes:
      - ./data:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 4000
    container_name: backend
    volumes:
      - "./backend:/srv/server"
    ports:
      - "4000:4000"
    depends_on:
      - database
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./client:/srv/client"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:4000
    depends_on:
      - backend
